### ISSUE TITLE
Choosing to save document hangs application

### ISSUE THREAD

**Issue by vegaasen** [evolus/pencil#243] opened 2017-02-02 08:32 UTC
* Operating system: Windows 7 64bit
* Pencil version: 3.0.0-rc.1

# The issue

_Important: This does not happen all the time_

From time to time, when saving changes to the document, the application stalls completely, rendering the whole UI unusable.
If choosing to close the applicating using the OS-specific "Close"-button (located in the upmost right corner[Windows]), the application dialog representing "**Do you want to save your work?**" pops up. However, neither of the buttons is clickable (Save, Discard, Cancel). 

We tried waiting for a period of time (say: 10 minutes) - the application was still stale. This results in none of the work done to the document is saved. The only method that works - in regards to closing the application - is to actually choose the process and kill it. This, obviously, invalidates all your work and changes to the document are not reflected 👎.

Let me know if I can generate some debugging logs or whatever, I'd be happy to do so!

Regards,
Vegard

**Comment by dgthanhan** [comment] 2017-02-06 03:24
This looks like the previous save got an error during the process without a correct error handling. One of the ways to debug this is that you help us first find the reliable way to reproduce the case. Opening the developer console before the issue happens will help gather the error log and this will help us a lot in fixing them.

**Comment by vegaasen** [comment] 2017-02-07 07:37
Hia, I'll try to capture the error next time it happens. Noticed the bug on some of my team-mates' computers as well (running the same OS, on the same platform).

**Comment by vegaasen** [comment] 2017-02-07 08:06
It actually seems like there is not much stuff going on in the log file. Is there any settings I can switch on to generate more debugging details? This issue happens quite a lot, actually :).
[pencil-1486453714036.txt](https://github.com/evolus/pencil/files/756949/pencil-1486453714036.txt)

Regards,
Vegard

**Comment by peluprvi** [comment] 2017-02-16 18:57
Same problem here on same OS (Windows 7 64bit installed on HDD) and Pencil 3.0.0-rc.2

Extra shapes installed:
Bootstrap, Android Lollipop and Material Icons.

Visible shapes:
Bootstrap, Android Lollipop, Material Icons, Basic Web Elements, Common Shapes and Flowchart.

I could (hardly) reproduce doing this:
- Keep navigating from some of your pages (I have 10 on the same project file)
- Click on menu and save it

Maybe the issue occurs when hitting "save" but the is thumbnail still processing. Or there is something with the extra shapes (Material Icons is large).

There is no CPU usage for Pencil.exe when it is freezed and the project file can be deleted, so it is not blocked or opened.

Developer Tools (no error log when it freezes):

![image](https://cloud.githubusercontent.com/assets/1561360/23034802/23054c54-f464-11e6-8ffa-96199752a167.png)

PS: The "Confirm" dialog can't be clicked, because there is some "waiting/loading overlay" actived, but I could navigate using "tab". The application closes when select the "Discard changes" button, but selecting "Cancel" or "Save" buttons does nothing.

**Comment by falco467** [comment] 2017-02-21 12:29
Same Problem here (Windows 7 64-bit) Pencil 3.0.0-rc2
On several Machines, sometimes using only Flowchart Shapes, sometimes with Bootstrap Shapes - Pencil regularly crashes on saving, if you work a long time (> 1 hour) without saving.

**Comment by dgthanhan** [comment] 2017-03-15 08:38
Latest implementation for Gnuzip Compressed (epgz) file format was enhanced to avoid errors. Could you please help test the code to see if this issue is still happening in the nightly builds?
http://pencil.evolus.vn/Nightly.html

**Comment by peluprvi** [comment] 2017-04-07 18:14
@dgthanhan still happening here on version 3.0.1

**Comment by Otiel** [comment] 2017-04-10 09:06
This happens to me several times a day, and it's honestly a major and annoying bug. I try to hit Ctrl+S every time I make a change in my project because otherwise I end up losing a lot of work.

I noticed the same behaviors as others have stated here:

No error shown in console.

The only responding control on the Pencil window is the close "x" button. This opens the "Save before closing window", but the mouse cursor has no action on its buttons. I tried hitting "Save" with my keyboard (<kbd>Tab</kbd>+<kbd>Tab</kbd>+<kbd>Tab</kbd>+<kbd>Enter</kbd>), but this only closes the "Save before closing window" and still leaves Pencil hanging. When hitting "Discard" on this window with the keyboard (<kbd>Tab</kbd>+<kbd>Enter</kbd>), Pencil is closed.

![Save before closing window](http://i.imgur.com/SuXig9e.png)

I could not find a way yet to reproduce this bug 100% of the time.

* Visible shapes: Common Shapes, Flowchart, Desktop - Sketchy GUI, Desktop - Prototype GUI, Desktop - Windows XP Widgets, Basic Web Elements, Material Icons
* Extra shapes installed: Desktop - GTK Widgets, Mobile - Android ICS, Modile - iOS UI Stencils, Mobile - iOS Wireframe
* OS: Windows 7 64bit
* Pencil 3.0.1

**Comment by shimpe** [comment] 2017-04-14 11:57
Same problem here with 3.0.1.
For some reason I didn't see any hangups with with 3.0.0rc2

**Comment by IWouldLikeToKnow** [comment] 2017-04-25 05:22
Hello,

Having the same issue with Version: 3.0.1, Windows 7 Enterprise.

![image](https://cloud.githubusercontent.com/assets/17772262/25369976/80d840f2-297f-11e7-971d-2413853bdd68.png)

**Comment by Otiel** [comment] 2017-04-26 16:33
This bug should be treated with high priority. I keep losing hours of work because I sometimes forget to hit <kbd>Ctrl</kbd><kbd>S</kbd> after every change I make. This is really frustrating.

I used Pencil 4-5 hours today, it crashed 4 times.

**Comment by jdugge** [comment] 2017-05-05 05:57
I can reproduce the save error in the following way:

1. Create a new Pencil document.
2. Paste the following text into the document (an ExtJS Panel copied from an existing document)

```
<g xmlns="http://www.w3.org/2000/svg" xmlns:p="http://www.evolus.vn/Namespace/Pencil" p:type="Shape" p:def="extJSKitchenSink:panel" p:sc="Frame Panel" id="8bd47d25510145d58e83788548ee1601" transform="matrix(1,0,0,1,24,32)" p:sizing-ox="0" p:sizing-oy="0" p:sizing-ow="581" p:sizing-oh="389"><p:metadata><p:property name="box"><![CDATA[581,389]]></p:property><p:property name="withIcon"><![CDATA[false]]></p:property><p:property name="withHeader"><![CDATA[true]]></p:property><p:property name="withFrame"><![CDATA[true]]></p:property><p:property name="fillColor"><![CDATA[#00ADA5FF]]></p:property><p:property name="content"><![CDATA[]]></p:property><p:property name="textColor"><![CDATA[#000000FF]]></p:property><p:property name="textFont"><![CDATA[Arial|normal|normal|13px|none]]></p:property><p:property name="title"><![CDATA[Verbrauch]]></p:property><p:property name="headerColor"><![CDATA[#FFFFFFFF]]></p:property><p:property name="headerFont"><![CDATA[Arial|bold|normal|13px|none]]></p:property><p:property name="textAlign"><![CDATA[0,0]]></p:property><p:property name="image"><![CDATA[26,26,ref://d6cd254670714b219d3796d069041211.png]]></p:property></p:metadata>         
            <rect stroke="none" rx="4" ry="4" p:name="frame" id="7bfe53a02c2e4652bbe6b3abc60fe8cd" x="0" y="0" width="581" height="389" style="fill: rgb(0, 173, 165); fill-opacity: 1; visibility: visible;"/>
            <rect stroke="none" style="fill: white;" p:name="rect" id="d4c4d0ce9bd14d94b7112e4dfd9a24eb" x="5" y="5" width="571" height="379"/>
            <g p:name="headerFrame" id="5916c79a19b54f61863152d3c3baae9e" style="visibility: visible;">
              <rect stroke="none" p:name="header" id="74e1bb7096c04e0ba21320aef2973540" x="0" y="5" width="581" height="31" style="fill: rgb(0, 173, 165); fill-opacity: 1;"/>
              <text p:name="title" id="910c4db214a74845a122509f58df608c" transform="translate(10,23)" style="fill: rgb(255, 255, 255); fill-opacity: 1; font-family: Arial; font-size: 13px; font-weight: bold; font-style: normal; text-decoration: none;">Verbrauch</text>
            </g>
            <foreignObject x="10" y="46" width="561" height="0" p:name="content" id="81696298aab64bcdab3a1496d5487660" style="fill: rgb(0, 0, 0); fill-opacity: 1; font-family: Arial; font-size: 13px; font-weight: normal; font-style: normal; text-decoration: none; text-align: left;"><div xmlns="http://www.w3.org/1999/xhtml"></div></foreignObject>
            <image xmlns:xlink="http://www.w3.org/1999/xlink" x="5" y="10" width="16" height="16" preserveAspectRatio="none" p:name="icon" id="c740520463814bb9a3d1fec7d01f033f" xlink:href="ref://d6cd254670714b219d3796d069041211.png" style="visibility: hidden; display: none;"/>
        </g>
```
3. Press Ctrl+S to save the document
4. Choose a location and filename 
5. Click save.

The cursor will change to "busy", but nothing will be written to the file. When clicking the "Close" button of the program, a dialog will pop up asking whether changes should be saved. No buttons in that dialog can be clicked, but using the Tab key you can navigate to the "Discard" button and push the button using the space bar.

![image](https://cloud.githubusercontent.com/assets/2399255/25735017/83e7667e-3168-11e7-8bec-0a2382d5e1de.png)

**Comment by dgthanhan** [comment] 2017-05-05 06:34
@jdugge Thanks for the information. This is in fact a really helpful data for us to resolve the issue. I can confirm that it is reproducible in my machine using your usecase.

**Comment by dgthanhan** [comment] 2017-05-05 06:50
Pencil uses two renderer processes and for some reasons, the backend renderer process failed in this case and the whole thing got stuck.

**Comment by dgthanhan** [comment] 2017-05-05 08:22
An invalid reference in the content causes the renderer to crash and the save process keeps waiting for a dead prcess.
A fix was pushed to 'development' branch. Your help to verify this issue is appreciated.

**Comment by Otiel** [comment] 2017-05-05 08:41
@dgthanhan Could you build a beta .exe package for Windows?

**Comment by dgthanhan** [comment] 2017-05-05 08:51
A set of nightly builds have just been created. You can try them out at:
http://pencil.evolus.vn/Nightly.html

**Comment by Otiel** [comment] 2017-05-05 08:53
Thanks. I will try that and report.

**Comment by jdugge** [comment] 2017-05-07 10:06
Just tried this out using our actual documents that used to keep crashing: works great!

Thank you so much for the fast reaction, and for making such a fantastic software available!

**Comment by dgthanhan** [comment] 2017-05-07 10:58
I'm happy to hear that it worked at your side. It's your input that helped us a lot in resolving this!

**Comment by shimpe** [comment] 2017-05-07 11:32
:1st_place_medal:  to @jdugge and @dgthanhan for getting to the bottom of this issue. I'm sure many people will sigh in relief after seeing this solved!

**Comment by peluprvi** [comment] 2017-05-17 15:47
2 hours of work without any crashes. Thanks a lot!

**Closed** 2017-07-18 02:05 UTC
