### ISSUE TITLE
"Link to" -> "Notthing" - Spelling mistake

### ISSUE THREAD

**Issue by BrutalCoding** [evolus/pencil#139] opened 2016-08-24 18:33 UTC
* Operating system: Windows 10
* Pencil version: 3.0.0 RC1

There is a spelling mistake, when you select a button and right click on it, go to "Link to" and you will see the option "Notthing", this should be "Nothing".

**Comment by dgthanhan** [comment] 2016-08-25 01:10
Close as duplicate of #89

**Closed by dgthanhan** 2016-08-25 01:10 UTC
