### ISSUE TITLE
Feature Request: When opening a pencil file from explorer, open that file in the program

### ISSUE THREAD

**Issue by fresheneesz** [evolus/pencil#297] opened 2017-04-07 06:09 UTC
Currently on the windows version (v 3.0.1), double clicking on one of my pencil files simply opens Pencil, but doesn't open the file I clicked on. I also can't drag the file onto the program to open it so its kind of a pain to open files. I'd like Pencil to open the file clicked on when Pencil opens.

**Comment by sebastianfilke** [comment] 2017-04-18 18:02
This is a duplicate of #295

**Comment by JohnSheppard** [comment] 2019-03-11 03:10
That #295 is for debian, but I guess ame thing. I will also state that it would be super good to have this feature. Issue #295 seems to state that older versions of pencil did in fact do this correctly....

**Comment by JohnSheppard** [comment] 2019-03-11 12:37
After testing it out, I can confirm that v3.0.0 RC does include this feature. I can double click on a pencil file from windows explorer and it will open.

**Comment by dgthanhan** [comment] 2019-03-28 02:34
This should be fixed in the latest code. [Nightly builds](http://pencil.evolus.vn/Nightly.html) should have this included.

**Closed by dgthanhan** 2019-03-28 02:34 UTC
